// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woxcxuhcrhyoeynmuhtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndveGN4dWhjcmh5b2V5bm11aHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTQ1NTEsImV4cCI6MjA1OTIzMDU1MX0.mJQj84y0yJAq4iKcI7x0lUaOSr6a3RdfQkXcIXCX9MM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);